import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { NavBar } from "../../components/navBar";
import { ProjectDetail } from "../../components/projectDetail";
// import {} from "next/font/google";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const projectCounts = api.project.getProjectCount.useQuery();
  const { data } = api.project.getAllProjects.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full flex-col bg-gradient-to-r from-red-500 to-green-500 p-10 lg:flex-row lg:p-20">
        <div className="   place-items-start ">
          <div className=" prose ">
            {" "}
            <h1>Garlic bread with cheese: What the science tells us</h1>
            <p>
              Vivamus convallis vel sem in lacinia. Maecenas faucibus massa ex,
              non accumsan quam rhoncus in. Quisque eleifend pharetra tristique.
              Nullam pellentesque mollis consequat. Vestibulum scelerisque,
              velit non malesuada placerat, velit augue pharetra magna, vel
              scelerisque arcu urna at nisi. Vivamus dapibus, diam in facilisis
              lacinia, nisl nibh cursus ligula, a interdum tortor erat eu ex.
            </p>
            <p>
              But a recent study shows that the celebrated appetizer may be
              linked to a series of rabies cases springing up around the
              country.
            </p>{" "}
          </div>
        </div>
        {/* <div className="divider lg:divider-horizontal"></div> */}
        <div className="card rounded-box  flex-grow place-items-center  ">
          <div className="mockup-code ">
            <pre data-prefix="$">
              <code>No. of projects in shardeum</code>
            </pre>
            <pre data-prefix=">" className="text-warning">
              <code>count: {projectCounts.data}</code>
            </pre>
            <pre data-prefix=">" className="text-success">
              <code>Done!</code>
            </pre>
          </div>
        </div>
      </main>
      <section>
        <ProjectDetail queryProjects={data!} />
      </section>
    </>
  );
};

export default Home;
