import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { ProjectDetail } from "../../components/projectDetail";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const projectCounts = api.project.getProjectCount.useQuery();
  const { data } = api.project.getAllProjects.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav>
          <Link href="/submit">Submit</Link>
        </nav>
        <h1>Count : {projectCounts.data}</h1>
        <Link href="/categories/gaming"> gaming</Link>
        <Link href="/categories/defi"> defi</Link>
        <Link href="/categories/nft"> nft</Link>
        <Link href="/categories/other"> other</Link>
        <ProjectDetail queryProjects={data!} />
      </main>
    </>
  );
};

export default Home;
